"use strict";
let estaChovendo = false;
estaChovendo = true;
let idade = 30;
let altura = 1.92;
const nacionalidade = 'brasileira';
const colegas = ['lucas', 'jonas'];
const tecnologias = ['html', 'css', 'js'];
const notas = [7, 9, 5, 8];
const lista = ['Eduardo', true, 30];
let idadeDoHoff = 27;
idadeDoHoff = '27 anos';
let dadosDaApi;
dadosDaApi = 10;
dadosDaApi = true;
dadosDaApi = [1, 2, 3];
dadosDaApi = 'string';
let curso = 'front-end';
